name: Deploy to GCP VM

on:
  push:
    branches:
      - main # Or your main branch name

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: 1. Checkout Code
      uses: actions/checkout@v3

    - name: 2. Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: 3. Pull Latest Changes
      run: |
        cd /home/malayjain1234/CCD-AI
        git pull

    - name: 4. Install Dependencies
      run: |
        cd /home/malayjain1234/CCD-AI
        source venv/bin/activate
        pip install -r requirements.txt

    - name: 5. Build the AI Knowledge Base
      run: |
        cd /home/malayjain1234/CCD-AI
        source venv/bin/activate
        python3 build_db.py
      env:
        GOOGLE_API_KEY_1: ${{ secrets.GOOGLE_API_KEY_1 }}

    - name: 6. Restart the Application
      run: |
        echo "Restarting the Gunicorn server..."
        # This will find and stop the old server, then start a new one in tmux
        cd /home/malayjain1234/CCD-AI
        tmux kill-session -t chatbot || true
        tmux new -d -s chatbot "source venv/bin/activate && gunicorn --bind 0.0.0.0:8080 run:app"
